### PR TITLE
Add support for oraclejdk10.

### PR DESCRIPTION
**Pull request by javadev**

### CODE REVIEW

**Comment by PromanSEW** [comment]
Build failed:
https://travis-ci.org/aNNiMON/Lightweight-Stream-API/jobs/392640816#L705-L745
8 tests failed

**Comment by PromanSEW** [comment]
https://github.com/mockito/mockito/pull/1356
Mockito 2.17.7
Last version: 2.18.9
https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md

**Comment by javadev** [comment]
```
com.annimon.stream.test.mockito.OptionalMatcherTest > testAnyPresentObjectOptionalWhenStubbing FAILED
    org.mockito.exceptions.base.MockitoException at OptionalMatcherTest.java:52
        Caused by: java.lang.UnsupportedOperationException at OptionalMatcherTest.java:52
            Caused by: java.lang.IllegalArgumentException at OptionalMatcherTest.java:52
com.annimon.stream.test.mockito.OptionalMatcherTest > testAnyEmptyObjectOptionalWhenVerifying FAILED
    org.mockito.exceptions.base.MockitoException at OptionalMatcherTest.java:115
        Caused by: java.lang.UnsupportedOperationException at OptionalMatcherTest.java:115
            Caused by: java.lang.IllegalArgumentException at OptionalMatcherTest.java:52
com.annimon.stream.test.mockito.OptionalMatcherTest > testAnyEmptyStringOptionalWhenStubbing FAILED
    org.mockito.exceptions.base.MockitoException at OptionalMatcherTest.java:125
        Caused by: java.lang.UnsupportedOperationException at OptionalMatcherTest.java:125
            Caused by: java.lang.IllegalArgumentException at OptionalMatcherTest.java:52
com.annimon.stream.test.mockito.OptionalMatcherTest > testAnyPresentObjectOptionalWhenVerifying FAILED
    org.mockito.exceptions.base.MockitoException at OptionalMatcherTest.java:61
        Caused by: java.lang.UnsupportedOperationException at OptionalMatcherTest.java:61
            Caused by: java.lang.IllegalArgumentException at OptionalMatcherTest.java:52
com.annimon.stream.test.mockito.OptionalMatcherTest > testAnyPresentStringOptionalWhenStubbing FAILED
    org.mockito.exceptions.base.MockitoException at OptionalMatcherTest.java:71
        Caused by: java.lang.UnsupportedOperationException at OptionalMatcherTest.java:71
            Caused by: java.lang.IllegalArgumentException at OptionalMatcherTest.java:52
com.annimon.stream.test.mockito.OptionalMatcherTest > testAnyEmptyStringOptionalWhenVerifying FAILED
    org.mockito.exceptions.base.MockitoException at OptionalMatcherTest.java:134
        Caused by: java.lang.UnsupportedOperationException at OptionalMatcherTest.java:134
            Caused by: java.lang.IllegalArgumentException at OptionalMatcherTest.java:52
com.annimon.stream.test.mockito.OptionalMatcherTest > testAnyEmptyObjectOptionalWhenStubbing FAILED
    org.mockito.exceptions.base.MockitoException at OptionalMatcherTest.java:106
        Caused by: java.lang.UnsupportedOperationException at OptionalMatcherTest.java:106
            Caused by: java.lang.IllegalArgumentException at OptionalMatcherTest.java:52
com.annimon.stream.test.mockito.OptionalMatcherTest > testAnyPresentStringOptionalWhenVerifying FAILED
    org.mockito.exceptions.base.MockitoException at OptionalMatcherTest.java:80
        Caused by: java.lang.UnsupportedOperationException at OptionalMatcherTest.java:80
            Caused by: java.lang.IllegalArgumentException at OptionalMatcherTest.java:52
110 tests completed, 8 failed
```

**Comment by PromanSEW** [comment]
@javadev Why?

**Comment by javadev** [comment]
@PromanSEW I added a comment to the issue https://github.com/aNNiMON/Lightweight-Stream-API/issues/157

**Pull request closed without merging**
