### PR TITLE
Add single() method to Stream

### PR DESCRIPTION
**Pull request by xsveda**

### CODE REVIEW

**Comment by aNNiMON** [comment]
Thank you for PR. Can you provide any use case for this operation?

**Comment by xsveda** [comment]
The `single()` method is quite similar to `findFirst()`. You  use it when you need more confidence in the state of a stream and when you want to emphasize that it is a failure when a stream has more then one element, i.e.:
```java
    public Optional<Mother> findMotherFor(Child child) {
        return Stream.of(mothers)
                .filter(mother -> mother.giveBirthTo(child))
                .single();
    }
```
If a stream would contain more then one element after filtering there is something very wrong.

**Comment by xsveda** [comment]
I've just realize that there is a similar `single()` operator in [RxJava's Observable](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Observable.java) that throws a `NoSuchElementException` when no item is emited. To match thich behavior we should rename current `Stream.single()` method to `Stream.findSingle()` and provide another more strict `Stream.single()` method.

**Comment by aNNiMON** [comment]
Thank you for explanation. Yes, we should adhere the naming convention when search method that returns `Optional` must have `find*` prefix.
By the way, don't forget to fix javadoc by adding `@throws IllegalStateException` line.

**Comment by aNNiMON** [comment]
Nice :+1:

**Pull request merged**
