### PR TITLE
New indexed features

### PR DESCRIPTION
**Pull request by PromanSEW**
Features and PR notes:
- [X] Indexed predicates
- [x] Indexed functions
- [x] Indexed consumers
- [x] New methods in `IntStream`, `LongStream`, `DoubleStream` (needs discussion):

- `filterIndexed`
- `mapIndexed`
Maybe implement these features as custom operators only in tests, see https://github.com/aNNiMON/Lightweight-Stream-API/issues/149#issuecomment-341912941

- [x] Tests

Relates to #120, #149

**Note:** First commit is simply merging `master` to my fork for using actual codebase

### CODE REVIEW

**Comment by aNNiMON** [comment]
Okay, I see you really need indexed operators for primitives. Finish with tests and I'll implement `filterIndexed` and `mapIndexed` operator. Then I plan to measure performance and compare results with any existing solution.

**Comment by aNNiMON** [comment]
@PromanSEW I'll review your tests soon.

I've pushed branch with implemented `filterIndexed` and [JMH benchmarks](https://github.com/aNNiMON/Lightweight-Stream-API/blob/filterIndexed-jmh/stream/src/jmh/java/com/annimon/stream/IndexedBenchmarks.java). To run benchmarks use `jmh` task:
`gradlew clean :stream:jmh`

Here's my results:
Laptop: Windows 7, Intel Pentium B960 @ 2.20 GHz. Oracle JDK 9.
```
Benchmark                       (size)   Mode  Cnt      Score      Error  Units
boxedFilterIndexed               10000  thrpt   10  12653,493 ±  678,506  ops/s
primitiveFilterIndexed           10000  thrpt   10  12251,112 ± 1513,192  ops/s
boxedFilterIndexedAndMap         10000  thrpt   10   9855,125 ±  589,901  ops/s
primitiveFilterIndexedAndMap     10000  thrpt   10   9141,676 ±  701,406  ops/s

boxedFilterIndexed            10000000  thrpt   10     11,628 ±    1,092  ops/s
primitiveFilterIndexed        10000000  thrpt   10     13,557 ±    1,456  ops/s
boxedFilterIndexedAndMap      10000000  thrpt   10      7,093 ±    1,115  ops/s
primitiveFilterIndexedAndMap  10000000  thrpt   10      8,963 ±    0,315  ops/s

boxedFilterIndexed            10000000   avgt   10      0,158 ±    0,012   s/op
primitiveFilterIndexed        10000000   avgt   10      0,147 ±    0,002   s/op
boxedFilterIndexedAndMap      10000000   avgt   10      0,293 ±    0,172   s/op
primitiveFilterIndexedAndMap  10000000   avgt   10      0,236 ±    0,002   s/op
```

Server: Debian, Intel(R) Xeon(R) CPU X5650 @ 2.67GHz. Oracle JDK 8.
```
Benchmark                       (size)   Mode  Cnt      Score       Error  Units
boxedFilterIndexed               10000  thrpt   10  21449.664 ±  5587.182  ops/s
primitiveFilterIndexed           10000  thrpt   10  33937.983 ± 10134.962  ops/s
boxedFilterIndexedAndMap         10000  thrpt   10  11215.016 ±  2049.991  ops/s
primitiveFilterIndexedAndMap     10000  thrpt   10   7085.781 ±  1482.159  ops/s

boxedFilterIndexed            10000000  thrpt   10     22.086 ±     4.158  ops/s
primitiveFilterIndexed        10000000  thrpt   10     22.974 ±     4.163  ops/s
boxedFilterIndexedAndMap      10000000  thrpt   10     10.418 ±     2.278  ops/s
primitiveFilterIndexedAndMap  10000000  thrpt   10      8.736 ±     1.107  ops/s

boxedFilterIndexed            10000000   avgt   10      0.095 ±     0.011   s/op
primitiveFilterIndexed        10000000   avgt   10      0.093 ±     0.026   s/op
boxedFilterIndexedAndMap      10000000   avgt   10      0.245 ±     0.058   s/op
primitiveFilterIndexedAndMap  10000000   avgt   10      0.215 ±     0.028   s/op
```

On `thrpt` benchmarks higher `Score` is better. On `avgt` lesser score is better.

You can add some real-world examples to benchmark them if you want.

**Comment by PromanSEW** [comment]
@aNNiMON I look when I will have time. I can provide example where I used `IndexedIntPredicate` for filtering `IntStream`
Any requested changes for this PR? I think these interfaces are useful.

**Comment by aNNiMON** [comment]
I've just tested [this solution](https://github.com/aNNiMON/Lightweight-Stream-API/issues/120#issuecomment-309593005). Here's results (intIndexedFilter) on 10,000,000 elements array:

```
Benchmark                       Mode  Cnt   Score   Error  Units
boxedFilterIndexed             thrpt   10  23.860 ± 0.299  ops/s
intIndexedFilter               thrpt   10   7.849 ± 1.186  ops/s
primitiveFilterIndexed         thrpt   10  25.444 ± 1.812  ops/s

boxedFilterIndexedAndMap       thrpt   10   9.874 ± 1.734  ops/s
intIndexedFilterAndMap         thrpt   10   4.302 ± 0.558  ops/s
primitiveFilterIndexedAndMap   thrpt   10  10.101 ± 0.649  ops/s
```

`Stream<IndexedInt> IntStream,indexed()` is about 2x slow, while primitive and boxed solutions are almost equal.

**Comment by PromanSEW** [comment]
@aNNiMON I think that `mapIndexed` and `filterIndexed` are redundant as of equality benchmark results for primitive and boxed implementations. `IndexedInt` is a bad idea. Using `boxed()` implementation is enough

**Comment by PromanSEW** [comment]
Here is my benchmark results
MacBook Pro Mid 2014, macOS 10.13.4
Intel Core i5-4288U 2.6 GHz. Oracle JDK 8
```
Benchmark                                         (size)   Mode  Cnt   Score   Error  Units
IndexedBenchmarks.boxedFilterIndexed            10000000  thrpt   10  25,308 ± 9,393  ops/s
IndexedBenchmarks.boxedFilterIndexedAndMap      10000000  thrpt   10  16,098 ± 2,556  ops/s
IndexedBenchmarks.primitiveFilterIndexed        10000000  thrpt   10  41,294 ± 5,914  ops/s
IndexedBenchmarks.primitiveFilterIndexedAndMap  10000000  thrpt   10  14,448 ± 0,526  ops/s
IndexedBenchmarks.boxedFilterIndexed            10000000   avgt   10   0,053 ± 0,003   s/op
IndexedBenchmarks.boxedFilterIndexedAndMap      10000000   avgt   10   0,120 ± 0,019   s/op
IndexedBenchmarks.primitiveFilterIndexed        10000000   avgt   10   0,045 ± 0,002   s/op
IndexedBenchmarks.primitiveFilterIndexedAndMap  10000000   avgt   10   0,132 ± 0,010   s/op
```

**Comment by aNNiMON** [comment]
@PromanSEW since most of the library users are Android developers, I think I should care about heap memory. Unfortunately. JMH can't benchmark memory allocation, maybe I should try [jamm](https://github.com/jbellis/jamm).

Anyway, I'm going to implement `filterIndexed`, `mapIndexed` (not `mapTo*Indexed`) and probably `forEachIndexed`.

**Pull request merged**
