### PR TITLE
IntStream implementation, backport of Random methods(which use IntStream), SpinedBuffer for ints for quick collection of  and minimum memory allocations

### PR DESCRIPTION
**Pull request by andrey-shikhov**
This is my backport for IntStream from Java 8,the main goal was to be as closest as possible to original api.
 In my projects(android) int[] arrays used a lot and generic Stream for my opinion is very expensive in terms of garbage generation. Also, I have ported handy Random methods to operate on random generator like a stream, which seems to be a natural way to do it.

### CODE REVIEW

**Comment by aNNiMON** [comment]
Thanks! I'll check your changes soon. The reason I didn't add primitive streams earlier is in larger size of the library. But apparently it's time to enlarge library size for the performance sake.

**Comment by andrey-shikhov** [comment]
When size of application matters usually proguard is used, so if IntStream is not used then proguard will remove all related classes from destination. But when there are a lot of operations on primitive arrays(j2me/android) wrapping every int into Integer and collecting results into ArrayList is expensive and using specialized stream is likely a must.

**Comment by aNNiMON** [comment]
Ok, I think I can merge your pull request into separate branch for further development after these small changes:

- [ ] there's no need to place int functions in separate package, please move them to `stream.function`
- [ ] some of the tests prints output to stdout
- [ ] test private constructors with hamcrest matcher, e.g. `assertThat(IntPredicate.Util.class, hasOnlyPrivateConstructors());`
- [ ] fix imports ;)

----

I also made benchmarks:


<details>
 <summary>Benchmark source</summary>
```java
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.annotations.OutputTimeUnit;
import org.openjdk.jmh.annotations.Scope;
import org.openjdk.jmh.annotations.Setup;
import org.openjdk.jmh.annotations.State;
import org.openjdk.jmh.runner.Runner;
import org.openjdk.jmh.runner.RunnerException;
import org.openjdk.jmh.runner.options.Options;
import org.openjdk.jmh.runner.options.OptionsBuilder;

@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.MILLISECONDS)
@State(Scope.Benchmark)
public class LsaStreamBenchmarks {

    volatile int counts = 9999999;
    int[] array = new int[counts];
    volatile List<Integer> list = new ArrayList<>(counts);

    @Setup
    public void setup() {
        populate(list);
    }

    public void populate(List<Integer> list) {
        for (int i = 0; i < counts; i++) {
            if (i < counts / 2) {
                array[i] = i;
                list.add(i, i);
            } else {
                array[i] = i - counts;
                list.add(i, i - counts);
            }
        }
    }

    @Benchmark
    public int forSumIntegers() {
        int result = 0;
        for (int i = 0; i < array.length; i++) {
            result += array[i];
        }
        return result;
    }

    @Benchmark
    public int forEachSumIntegers() {
        int result = 0;
        for (int value : array) {
            result += value;
        }
        return result;
    }

    @Benchmark
    public int forEachSumIntegersList() {
        int result = 0;
        for (int value : list) {
            result += value;
        }
        return result;
    }

    @Benchmark
    public int javaIntStreamSumIntegersWithReduce() {
        int result = java.util.stream.IntStream.of(array)
                .reduce(0, (a, b) -> a + b);
        return result;
    }

    @Benchmark
    public int javaIntStreamSumIntegers() {
        int result = java.util.stream.IntStream.of(array)
                .sum();
        return result;
    }

    @Benchmark
    public int javaStreamSumIntegers() {
        int result = list.stream()
                .reduce(0, (a, b) -> a + b);
        return result;
    }

    @Benchmark
    public int lsaStreamSumIntegers() {
        int result = com.annimon.stream.Stream.of(list)
                .reduce(0, (a, b) -> a + b);
        return result;
    }

    @Benchmark
    public int lsaIntStreamSumIntegersWithReduce() {
        int result = com.annimon.stream.IntStream.of(array)
                .reduce(0, (a, b) -> a + b);
        return result;
    }

    @Benchmark
    public int lsaIntStreamSumIntegers() {
        int result = com.annimon.stream.IntStream.of(array)
                .sum();
        return result;
    }

    public static void main(String[] args) throws RunnerException {
        Options opt = new OptionsBuilder()
                .include(LsaStreamBenchmarks.class.getSimpleName())
                .warmupIterations(3)
                .measurementIterations(5)
                .forks(1)
                .build();

        new Runner(opt).run();
    }
}
```
</details>
```
Benchmark                             Mode  Cnt    Score   Error  Units
forEachSumIntegers                    avgt    5    5,953 ? 0,452  ms/op
forEachSumIntegersList                avgt    5   23,939 ? 0,399  ms/op
forSumIntegers                        avgt    5    5,888 ? 0,081  ms/op
javaIntStreamSumIntegers              avgt    5    5,967 ? 0,119  ms/op
javaIntStreamSumIntegersWithReduce    avgt    5    5,930 ? 0,087  ms/op
javaStreamSumIntegers                 avgt    5   93,953 ? 2,850  ms/op
lsaIntStreamSumIntegers               avgt    5    5,933 ? 0,051  ms/op
lsaIntStreamSumIntegersWithReduce     avgt    5    5,980 ? 0,099  ms/op
lsaStreamSumIntegers                  avgt    5  158,032 ? 2,874  ms/op
```

**Comment by aNNiMON** [comment]
One more question: can we create constant field for PrimitiveIterator in IntStream.empty() or it must always be created?

**Comment by aNNiMON** [comment]
Fine!

**Pull request merged**
