### PR TITLE
Switching to JaCoCo

### PR DESCRIPTION
**Pull request by aNNiMON**
TODO:  
 - [ ] determine how to ignore some classes from report

### CODE REVIEW

**Comment by javadev** [comment]
❤️

**Comment by aNNiMON** [comment]
Ignoring classes still doesn't work.  I've tried all solutions I found.

**Comment by javadev** [comment]
I found  a solution how to exclude embedded static classes from coverage report.

https://stackoverflow.com/questions/50442279/how-do-i-exclude-a-method-from-jacoco-test-coverage-report-in-android-project

**Comment by aNNiMON** [comment]
@javadev still not found a way to ignore classes. Solution from link you provided uses `<exclude>**/Xml$Document.class</exclude>` which won't work in Gradle multiproject (or won't work at all).

**Pull request merged**
